import { typecheckPlugin } from "@jgoz/esbuild-plugin-typecheck";
import builtins from "builtin-modules";
import esbuild from "esbuild";
import { copy } from "esbuild-plugin-copy";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const watch = !prod && process.argv[2] !== "nowatch";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/index.ts"],
  bundle: true,
  loader: {
    ".png": "binary",
    ".jpg": "binary",
    ".wasm": "binary",
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2023",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [
    inlineWorkerPlugin({
      sourcemap: prod ? false : "inline", // inline workers with sourcemaps in dev mode}),
      treeShaking: true,
      target: "es2023",
      conditions: ["worker"],
    }),
    typecheckPlugin({ watch }),
    copy({
      // this is equal to process.cwd(), which means we use cwd path as base path to resolve `to` path
      // if not specified, this plugin uses ESBuild.build outdir/outfile options as base path.
      resolveFrom: "cwd",
      assets: [
        {
          from: ["./manifest.json"],
          to: [
            "./test-vault/.obsidian/plugins/iron-vault/manifest.json",
            "./docs/.obsidian/plugins/iron-vault/manifest.json",
          ],
        },
        {
          from: ["./.hotreload"],
          to: [
            "./test-vault/.obsidian/plugins/iron-vault/.hotreload",
            "./docs/.obsidian/plugins/iron-vault/.hotreload",
          ],
        },
        {
          from: ["./main.js"],
          to: [
            "./docs/.obsidian/plugins/iron-vault/main.js",
            "./test-vault/.obsidian/plugins/iron-vault/main.js",
          ],
        },
      ],
      watch,
    }),
  ],
});

const cssCtx = await esbuild.context({
  entryPoints: ["src/styles.css"],
  bundle: true,
  sourcemap: prod ? false : "inline",
  outfile: "styles.css",
  loader: {
    ".svg": "dataurl",
  },
  target: "chrome120",
  plugins: [
    copy({
      // this is equal to process.cwd(), which means we use cwd path as base path to resolve `to` path
      // if not specified, this plugin uses ESBuild.build outdir/outfile options as base path.
      resolveFrom: "cwd",
      assets: [
        {
          from: ["./styles.css"],
          to: [
            "./test-vault/.obsidian/plugins/iron-vault/styles.css",
            "./docs/.obsidian/plugins/iron-vault/styles.css",
          ],
        },
      ],
      watch,
    }),
  ],
});

if (!watch) {
  await Promise.all([context.rebuild(), cssCtx.rebuild()]);
  process.exit(0);
} else {
  await Promise.all([context.watch(), cssCtx.watch()]);
}
