packages:
  - packages/*

catalog:
  '@3d-dice/dice-box': ^1.1.4
  '@3d-dice/theme-smooth': ^0.2.1
  '@codemirror/language': ^6.10.8
  '@codemirror/view': ^6.38.1
  '@datasworn/core': 0.1.0-0
  '@datasworn/ironsworn-classic': 0.1.0-0
  '@datasworn/ironsworn-classic-delve': 0.1.0-0
  '@datasworn/starforged': 0.1.0-0
  '@datasworn/sundered-isles': 0.1.0-0
  '@eslint/js': ^9.34.0
  '@jgoz/esbuild-plugin-typecheck': ^4.0.3
  '@nrsk/sigma': ^3.8.0
  '@preact/signals-core': ^1.12.1
  '@types/electron': npm:@ophidian/electron-types@^24.3.1
  '@types/js-yaml': ^4.0.9
  '@types/lodash.isequal': ^4.5.8
  '@types/lodash.isequalwith': ^4.4.9
  '@types/lodash.ismatch': ^4.4.9
  '@types/lodash.merge': ^4.6.9
  '@types/mdast': ^4.0.4
  '@types/node': ^20.17.24
  '@types/obsidian-typings': npm:obsidian-typings@^3.12.1
  '@types/semver': ^7.7.0
  '@types/sortablejs': ^1.15.8
  '@types/unist': ^3.0.3
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  builtin-modules: ^5.0.0
  emittery: ^1.1.0
  esbuild: ^0.25.9
  esbuild-plugin-copy: ^2.1.1
  esbuild-plugin-inline-worker: ^0.1.1
  eslint: ^9.34.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  handlebars: ^4.7.8
  idb: ^8.0.2
  immer: ^10.1.1
  js-yaml: ^4.1.0
  jsdom: ^26.1.0
  kdljs: ^0.2.0
  lit-html: ^3.2.1
  lodash.isequal: ^4.5.0
  lodash.isequalwith: ^4.4.0
  lodash.ismatch: ^4.4.0
  lodash.merge: ^4.6.2
  loglevel: ^1.9.2
  mdast-util-from-markdown: ^2.0.2
  mdast-util-frontmatter: ^2.0.1
  mdast-util-gfm: ^3.1.0
  mdast-util-to-markdown: ^2.1.2
  micromark-extension-frontmatter: ^2.0.0
  micromark-extension-gfm: ^3.0.0
  minisearch: ^7.1.2
  obsidian: ^1.8.7
  prettier: ^3.6.2
  semver: ^7.7.2
  sortablejs: ^1.15.6
  true-myth: ^9.1.0
  tslib: ^2.8.1
  typescript: ^5.9.2
  typescript-eslint: ^8.42.0
  unist-util-is: ^6.0.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vitest-tsconfig-paths: ^3.4.1
  yaml: ^2.8.1
  zod: ^4.1.5
